apiVersion: apps/v1
kind: Deployment
metadata:
  name: piazza-deployment
  labels:
    app: piazza 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: piazza
  template:
    metadata:
      labels:
        app: piazza
    spec:
      containers:
      - name: piazza
        image: stanleyo/piazza
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
